In [ ]:
import tensorflow as tf

# **Manipulating Tensors** #
**Basic tensor operations**

+, -, *, /

In [ ]:
# Adding values to tensors
tensor = tf.constant([[1, 2], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [ ]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# The only way to change it is
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
# Back to original
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-19, -18],
       [-17, -16]], dtype=int32)>

**Tensorflow built-in functions**

In [ ]:
# We can also use tensorflow built-in funstions like
print(tf.add(tensor, 10))
print(tf.subtract(tensor, 10))
print(tf.multiply(tensor, 10))
print(tf.divide(tensor, 10))

tf.Tensor(
[[21 22]
 [23 24]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[110 120]
 [130 140]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.1 1.2]
 [1.3 1.4]], shape=(2, 2), dtype=float64)


In [ ]:
# Still the original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>